### ISSUE TITLE
error starting sim

### ISSUE THREAD

**Issue by ironmann250** [haofoss/slight-fimulator#9]
hi, i wanted to use this simulator to programmatically control it, to use with my Stewart platform robot, to ultimately make a physical flight sim, but when i run it and click start (running on windows 11, python 3.9.7) i get the following error
 `pygame 2.1.2 (SDL 2.0.18, Python 3.9.7)
Hello from the pygame community. https://www.pygame.org/contribute.html
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
Traceback (most recent call last):
  File "c:\slight-fimulator-3.1.2\slight-fimulator-3.1.2\__main__.py", line 43, in <module>
    g.mainloop(a)
  File "c:\slight-fimulator-3.1.2\slight-fimulator-3.1.2\game.py", line 337, in mainloop
    self.GAME_LOOPS[self.stage](self) # Runs the correct loop
  File "c:\slight-fimulator-3.1.2\slight-fimulator-3.1.2\game.py", line 1190, in game_loop_main
    self.control_plane()
  File "c:\slight-fimulator-3.1.2\slight-fimulator-3.1.2\game.py", line 874, in control_plane
    self.plane.roll_level -= ((self.keys_held[self.controls[
IndexError: list index out of range
`

**Comment by MasterofNumbers17** [comment]
Hi,

I was able to reproduce your issue on my computer & I've pushed a fix that works on my system (Windows 10, Python 3.9.6, Pygame 2.1.2).  It seems the problem had something to do with an upgrade to Pygame (v1 to v2).  If it also works on your system, great!  If it doesn't, please reopen this issue or create a new one and let me know what's going wrong.

Also, I should mention that this is a 4 year old high school project - so I can't guarantee that any of the mechanics or values are realistic or will work on your Stewart platform robot.

Good luck! // Bonne chance!

**Comment by ironmann250** [comment]
Hi many thanks,
it works great, now time to modify it for my needs!
